        <div class="migrationAlert">
            <h2>NEW: SciServer Betelgeuse (v2.0.0)!</h2>
            <p>
				We are proud to announce a new release of the SciServer online science platform! The new "Betelgeuse" release has many new features to manage and share big data resources. Learn about the changes on the
				<a href="http://www.sciserver.org/release/sciserver-v2/">SciServer website</a>!
			</p>
        </div>
